export const categories = [
  {
    id: 1,
    name: "About",
    g_id: "about",
    sourcefrom: "guardian",
  },
  {
    id: 2,
    name: "Animals farmed",
    g_id: "animals-farmed",
    sourcefrom: "guardian",
  },
  {
    id: 3,
    name: "Art and design",
    g_id: "artanddesign",
    sourcefrom: "guardian",
  },
  {
    id: 4,
    name: "Australia news",
    g_id: "australia-news",
    sourcefrom: "guardian",
  },
  {
    id: 5,
    name: "Better Business",
    g_id: "better-business",
    sourcefrom: "guardian",
  },
  {
    id: 6,
    name: "Books",
    g_id: "books",
    sourcefrom: "guardian",
  },
  {
    id: 7,
    name: "Business",
    g_id: "business",
    sourcefrom: "guardian",
  },
  {
    id: 8,
    name: "Business to business",
    g_id: "business-to-business",
    sourcefrom: "guardian",
  },
  {
    id: 9,
    name: "Cardiff",
    g_id: "cardiff",
    sourcefrom: "guardian",
  },
  {
    id: 10,
    name: "Children's books",
    g_id: "childrens-books-site",
    sourcefrom: "guardian",
  },
  {
    id: 11,
    name: "Cities",
    g_id: "cities",
    sourcefrom: "guardian",
  },
  {
    id: 12,
    name: "Opinion",
    g_id: "commentisfree",
    sourcefrom: "guardian",
  },
  {
    id: 13,
    name: "Community",
    g_id: "community",
    sourcefrom: "guardian",
  },
  {
    id: 14,
    name: "Crosswords",
    g_id: "crosswords",
    sourcefrom: "guardian",
  },
  {
    id: 15,
    name: "Culture",
    g_id: "culture",
    sourcefrom: "guardian",
  },
  {
    id: 16,
    name: "Culture Network",
    g_id: "culture-network",
    sourcefrom: "guardian",
  },
  {
    id: 17,
    name: "Culture professionals network",
    g_id: "culture-professionals-network",
    sourcefrom: "guardian",
  },
  {
    id: 18,
    name: "Edinburgh",
    g_id: "edinburgh",
    sourcefrom: "guardian",
  },
  {
    id: 19,
    name: "Education",
    g_id: "education",
    sourcefrom: "guardian",
  },
  {
    id: 20,
    name: "Guardian Enterprise Network",
    g_id: "enterprise-network",
    sourcefrom: "guardian",
  },
  {
    id: 21,
    name: "Environment",
    g_id: "environment",
    sourcefrom: "guardian",
  },
  {
    id: 22,
    name: "Extra",
    g_id: "extra",
    sourcefrom: "guardian",
  },
  {
    id: 23,
    name: "Fashion",
    g_id: "fashion",
    sourcefrom: "guardian",
  },
  {
    id: 24,
    name: "Film",
    g_id: "film",
    sourcefrom: "guardian",
  },
  {
    id: 25,
    name: "Food",
    g_id: "food",
    sourcefrom: "guardian",
  },
  {
    id: 26,
    name: "Football",
    g_id: "football",
    sourcefrom: "guardian",
  },
  {
    id: 27,
    name: "Games",
    g_id: "games",
    sourcefrom: "guardian",
  },
  {
    id: 28,
    name: "Global development",
    g_id: "global-development",
    sourcefrom: "guardian",
  },
  {
    id: 29,
    name: "Global Development Professionals Network",
    g_id: "global-development-professionals-network",
    sourcefrom: "guardian",
  },
  {
    id: 30,
    name: "Guardian Government Computing",
    g_id: "government-computing-network",
    sourcefrom: "guardian",
  },
  {
    id: 31,
    name: "Guardian Foundation",
    g_id: "guardian-foundation",
    sourcefrom: "guardian",
  },
  {
    id: 32,
    name: "Guardian Professional",
    g_id: "guardian-professional",
    sourcefrom: "guardian",
  },
  {
    id: 33,
    name: "Healthcare Professionals Network",
    g_id: "healthcare-network",
    sourcefrom: "guardian",
  },
  {
    id: 34,
    name: "Help",
    g_id: "help",
    sourcefrom: "guardian",
  },
  {
    id: 35,
    name: "Higher Education Network",
    g_id: "higher-education-network",
    sourcefrom: "guardian",
  },
  {
    id: 36,
    name: "Housing Network",
    g_id: "housing-network",
    sourcefrom: "guardian",
  },
  {
    id: 37,
    name: "Inequality",
    g_id: "inequality",
    sourcefrom: "guardian",
  },
  {
    id: 38,
    name: "Info",
    g_id: "info",
    sourcefrom: "guardian",
  },
  {
    id: 39,
    name: "Jobs",
    g_id: "jobsadvice",
    sourcefrom: "guardian",
  },
  {
    id: 40,
    name: "Katine",
    g_id: "katine",
    sourcefrom: "guardian",
  },
  {
    id: 41,
    name: "Law",
    g_id: "law",
    sourcefrom: "guardian",
  },
  {
    id: 42,
    name: "Leeds",
    g_id: "leeds",
    sourcefrom: "guardian",
  },
  {
    id: 43,
    name: "Life and style",
    g_id: "lifeandstyle",
    sourcefrom: "guardian",
  },
  {
    id: 44,
    name: "Local",
    g_id: "local",
    sourcefrom: "guardian",
  },
  {
    id: 45,
    name: "Local Leaders Network",
    g_id: "local-government-network",
    sourcefrom: "guardian",
  },
  {
    id: 46,
    name: "Media",
    g_id: "media",
    sourcefrom: "guardian",
  },
  {
    id: 47,
    name: "Media Network",
    g_id: "media-network",
    sourcefrom: "guardian",
  },
  {
    id: 48,
    name: "Membership",
    g_id: "membership",
    sourcefrom: "guardian",
  },
  {
    id: 49,
    name: "Money",
    g_id: "money",
    sourcefrom: "guardian",
  },
  {
    id: 50,
    name: "Music",
    g_id: "music",
    sourcefrom: "guardian",
  },
  {
    id: 51,
    name: "News",
    g_id: "news",
    sourcefrom: "guardian",
  },
  {
    id: 52,
    name: "Politics",
    g_id: "politics",
    sourcefrom: "guardian",
  },
  {
    id: 53,
    name: "Public Leaders Network",
    g_id: "public-leaders-network",
    sourcefrom: "guardian",
  },
  {
    id: 54,
    name: "Science",
    g_id: "science",
    sourcefrom: "guardian",
  },
  {
    id: 55,
    name: "Search",
    g_id: "search",
    sourcefrom: "guardian",
  },
  {
    id: 56,
    name: "Guardian Small Business Network",
    g_id: "small-business-network",
    sourcefrom: "guardian",
  },
  {
    id: 57,
    name: "Social Care Network",
    g_id: "social-care-network",
    sourcefrom: "guardian",
  },
  {
    id: 58,
    name: "Social Enterprise Network",
    g_id: "social-enterprise-network",
    sourcefrom: "guardian",
  },
  {
    id: 59,
    name: "Society",
    g_id: "society",
    sourcefrom: "guardian",
  },
  {
    id: 60,
    name: "Society Professionals",
    g_id: "society-professionals",
    sourcefrom: "guardian",
  },
  {
    id: 61,
    name: "Sport",
    g_id: "sport",
    sourcefrom: "guardian",
  },
  {
    id: 62,
    name: "Stage",
    g_id: "stage",
    sourcefrom: "guardian",
  },
  {
    id: 63,
    name: "Teacher Network",
    g_id: "teacher-network",
    sourcefrom: "guardian",
  },
  {
    id: 64,
    name: "Technology",
    g_id: "technology",
    sourcefrom: "guardian",
  },
  {
    id: 65,
    name: "From the Guardian",
    g_id: "theguardian",
    sourcefrom: "guardian",
  },
  {
    id: 66,
    name: "From the Observer",
    g_id: "theobserver",
    sourcefrom: "guardian",
  },
  {
    id: 67,
    name: "Travel",
    g_id: "travel",
    sourcefrom: "guardian",
  },
  {
    id: 68,
    name: "Guardian holiday offers",
    g_id: "travel/offers",
    sourcefrom: "guardian",
  },
  {
    id: 69,
    name: "Television & radio",
    g_id: "tv-and-radio",
    sourcefrom: "guardian",
  },
  {
    id: 70,
    name: "UK news",
    g_id: "uk-news",
    sourcefrom: "guardian",
  },
  {
    id: 71,
    name: "US news",
    g_id: "us-news",
    sourcefrom: "guardian",
  },
  {
    id: 72,
    name: "Wellness (Do NOT use)",
    g_id: "us-wellness",
    sourcefrom: "guardian",
  },
  {
    id: 73,
    name: "Voluntary Sector Network",
    g_id: "voluntary-sector-network",
    sourcefrom: "guardian",
  },
  {
    id: 74,
    name: "Weather",
    g_id: "weather",
    sourcefrom: "guardian",
  },
  {
    id: 75,
    name: "Wellness",
    g_id: "wellness",
    sourcefrom: "guardian",
  },
  {
    id: 76,
    name: "Women in Leadership",
    g_id: "women-in-leadership",
    sourcefrom: "guardian",
  },
  {
    id: 77,
    name: "Working in development",
    g_id: "working-in-development",
    sourcefrom: "guardian",
  },
  {
    id: 78,
    name: "World news",
    g_id: "world",
    sourcefrom: "guardian",
  },
  {
    id: 79,
    name: "Arts",
  },
  {
    id: 80,
    name: "Automobiles",
  },
  {
    id: 81,
    name: "Autos",
  },
  {
    id: 82,
    name: "Blogs",
  },
  {
    id: 83,
    name: "Booming",
  },
  {
    id: 84,
    name: "Business Day",
  },
  {
    id: 85,
    name: "Corrections",
  },
  {
    id: 86,
    name: "Crosswords & Games",
  },
  {
    id: 87,
    name: "Crosswords/Games",
  },
  {
    id: 88,
    name: "Dining & Wine",
  },
  {
    id: 89,
    name: "Dining and Wine",
  },
  {
    id: 90,
    name: "Editors' Notes",
  },
  {
    id: 91,
    name: "Entertainment",
  },
  {
    id: 92,
    name: "Fashion & Style",
  },
  {
    id: 93,
    name: "Front Page",
  },
  {
    id: 94,
    name: "Genral",
  },
  {
    id: 95,
    name: "Giving",
  },
  {
    id: 96,
    name: "Global Home",
  },
  {
    id: 97,
    name: "Great Homes & Destinations",
  },
  {
    id: 98,
    name: "Great Homes and Destinations",
  },
  {
    id: 99,
    name: "Health",
  },
  {
    id: 100,
    name: "Home & Garden",
  },
  {
    id: 101,
    name: "Home and Garden",
  },
  {
    id: 102,
    name: "International Home",
  },
  {
    id: 103,
    name: "Job Market",
  },
  {
    id: 104,
    name: "Learning",
  },
  {
    id: 105,
    name: "Magazine",
  },
  {
    id: 106,
    name: "Movies",
  },
  {
    id: 107,
    name: "Multimedia",
  },
  {
    id: 108,
    name: "Multimedia/Photos",
  },
  {
    id: 109,
    name: "N.Y. / Region",
  },
  {
    id: 110,
    name: "N.Y./Region",
  },
  {
    id: 111,
    name: "NYRegion",
  },
  {
    id: 112,
    name: "NYT Now",
  },
  {
    id: 113,
    name: "National",
  },
  {
    id: 114,
    name: "New York",
  },
  {
    id: 115,
    name: "New York and Region",
  },
  {
    id: 116,
    name: "Obituaries",
  },
  {
    id: 117,
    name: "Olympics",
  },
  {
    id: 118,
    name: "Open",
  },
  {
    id: 119,
    name: "Paid Death Notices",
  },
  {
    id: 120,
    name: "Public Editor",
  },
  {
    id: 121,
    name: "Real Estate",
  },
  {
    id: 122,
    name: "Sports",
  },
  {
    id: 123,
    name: "Style",
  },
  {
    id: 124,
    name: "Sunday Magazine",
  },
  {
    id: 125,
    name: "Sunday Review",
  },
  {
    id: 126,
    name: "T Magazine",
  },
  {
    id: 127,
    name: "T:Style",
  },
  {
    id: 128,
    name: "The Public Editor",
  },
  {
    id: 129,
    name: "The Upshot",
  },
  {
    id: 130,
    name: "Theater",
  },
  {
    id: 131,
    name: "Times Topics",
  },
  {
    id: 132,
    name: "TimesMachine",
  },
  {
    id: 133,
    name: "Today's Headlines",
  },
  {
    id: 134,
    name: "Topics",
  },
  {
    id: 135,
    name: "U.S.",
  },
  {
    id: 136,
    name: "Universal",
  },
  {
    id: 137,
    name: "UrbanEye",
  },
  {
    id: 138,
    name: "Washington",
  },
  {
    id: 139,
    name: "Week in Review",
  },
  {
    id: 140,
    name: "World",
  },
  {
    id: 141,
    name: "Your Money",
  },
];

export const countries = [
  {
    id: 1,
    name: "United Arab Emirates",
    country_sm: "AE",
    otherNamesForTheCountry: ["UAE", "U.A.E"],
  },
  {
    id: 2,
    name: "Argentina",
    country_sm: "AR",
    otherNamesForTheCountry: [],
  },
  {
    id: 3,
    name: "Austria",
    country_sm: "AT",
    otherNamesForTheCountry: [],
  },
  {
    id: 4,
    name: "Australia",
    country_sm: "AU",
    otherNamesForTheCountry: [],
  },
  {
    id: 5,
    name: "Belgium",
    country_sm: "BE",
    otherNamesForTheCountry: [],
  },
  {
    id: 6,
    name: "Bulgaria",
    country_sm: "BG",
    otherNamesForTheCountry: [],
  },
  {
    id: 7,
    name: "Brazil",
    country_sm: "BR",
    otherNamesForTheCountry: [],
  },
  {
    id: 8,
    name: "Canada",
    country_sm: "CA",
    otherNamesForTheCountry: [],
  },
  {
    id: 9,
    name: "Switzerland",
    country_sm: "CH",
    otherNamesForTheCountry: [],
  },
  {
    id: 10,
    name: "China",
    country_sm: "CN",
    otherNamesForTheCountry: [],
  },
  {
    id: 11,
    name: "Colombia",
    country_sm: "CO",
    otherNamesForTheCountry: [],
  },
  {
    id: 12,
    name: "Cuba",
    country_sm: "CU",
    otherNamesForTheCountry: [],
  },
  {
    id: 13,
    name: "Czech Republic",
    country_sm: "CZ",
    otherNamesForTheCountry: [],
  },
  {
    id: 14,
    name: "Germany",
    country_sm: "DE",
    otherNamesForTheCountry: [],
  },
  {
    id: 15,
    name: "Egypt",
    country_sm: "EG",
    otherNamesForTheCountry: [],
  },
  {
    id: 16,
    name: "France",
    country_sm: "FR",
    otherNamesForTheCountry: [],
  },
  {
    id: 17,
    name: "United Kingdom",
    country_sm: "GB",
    otherNamesForTheCountry: ["UK", "Britain", "England"],
  },
  {
    id: 18,
    name: "Greece",
    country_sm: "GR",
    otherNamesForTheCountry: [],
  },
  {
    id: 19,
    name: "Hong Kong",
    country_sm: "HK",
    otherNamesForTheCountry: [],
  },
  {
    id: 20,
    name: "Hungary",
    country_sm: "HU",
    otherNamesForTheCountry: [],
  },
  {
    id: 21,
    name: "Indonesia",
    country_sm: "ID",
    otherNamesForTheCountry: [],
  },
  {
    id: 22,
    name: "Ireland",
    country_sm: "IE",
    otherNamesForTheCountry: [],
  },
  {
    id: 23,
    name: "Israel",
    country_sm: "IL",
    otherNamesForTheCountry: [],
  },
  {
    id: 24,
    name: "India",
    country_sm: "IN",
    otherNamesForTheCountry: [],
  },
  {
    id: 25,
    name: "Italy",
    country_sm: "IT",
    otherNamesForTheCountry: [],
  },
  {
    id: 26,
    name: "Japan",
    country_sm: "JP",
    otherNamesForTheCountry: [],
  },
  {
    id: 27,
    name: "South Korea",
    country_sm: "KR",
    otherNamesForTheCountry: [],
  },
  {
    id: 28,
    name: "Lithuania",
    country_sm: "LT",
    otherNamesForTheCountry: [],
  },
  {
    id: 29,
    name: "Latvia",
    country_sm: "LV",
    otherNamesForTheCountry: [],
  },
  {
    id: 30,
    name: "Morocco",
    country_sm: "MA",
    otherNamesForTheCountry: [],
  },
  {
    id: 31,
    name: "Mexico",
    country_sm: "MX",
    otherNamesForTheCountry: [],
  },
  {
    id: 32,
    name: "Malaysia",
    country_sm: "MY",
    otherNamesForTheCountry: [],
  },
  {
    id: 33,
    name: "Nigeria",
    country_sm: "NG",
    otherNamesForTheCountry: [],
  },
  {
    id: 34,
    name: "Netherlands",
    country_sm: "NL",
    otherNamesForTheCountry: [],
  },
  {
    id: 35,
    name: "Norway",
    country_sm: "NO",
    otherNamesForTheCountry: [],
  },
  {
    id: 36,
    name: "New Zealand",
    country_sm: "NZ",
    otherNamesForTheCountry: [],
  },
  {
    id: 37,
    name: "Philippines",
    country_sm: "PH",
    otherNamesForTheCountry: [],
  },
  {
    id: 38,
    name: "Poland",
    country_sm: "PL",
    otherNamesForTheCountry: [],
  },
  {
    id: 39,
    name: "Portugal",
    country_sm: "PT",
    otherNamesForTheCountry: [],
  },
  {
    id: 40,
    name: "Romania",
    country_sm: "RO",
    otherNamesForTheCountry: [],
  },
  {
    id: 41,
    name: "Serbia",
    country_sm: "RS",
    otherNamesForTheCountry: [],
  },
  {
    id: 42,
    name: "Russia",
    country_sm: "RU",
    otherNamesForTheCountry: [],
  },
  {
    id: 43,
    name: "Saudi Arabia",
    country_sm: "SA",
    otherNamesForTheCountry: [],
  },
  {
    id: 44,
    name: "Sweden",
    country_sm: "SE",
    otherNamesForTheCountry: [],
  },
  {
    id: 45,
    name: "Singapore",
    country_sm: "SG",
    otherNamesForTheCountry: [],
  },
  {
    id: 46,
    name: "Slovenia",
    country_sm: "SI",
    otherNamesForTheCountry: [],
  },
  {
    id: 47,
    name: "Slovakia",
    country_sm: "SK",
    otherNamesForTheCountry: [],
  },
  {
    id: 48,
    name: "Thailand",
    country_sm: "TH",
    otherNamesForTheCountry: [],
  },
  {
    id: 49,
    name: "Turkey",
    country_sm: "TR",
    otherNamesForTheCountry: [],
  },
  {
    id: 50,
    name: "Taiwan",
    country_sm: "TW",
    otherNamesForTheCountry: [],
  },
  {
    id: 51,
    name: "Ukraine",
    country_sm: "UA",
    otherNamesForTheCountry: [],
  },
  {
    id: 52,
    name: "United States",
    country_sm: "US",
    otherNamesForTheCountry: ["USA", "U.S.A", "America"],
  },
  {
    id: 53,
    name: "Venezuela",
    country_sm: "VE",
    otherNamesForTheCountry: [],
  },
  {
    id: 54,
    name: "South Africa",
    country_sm: "ZA",
    otherNamesForTheCountry: [],
  },
];

export const SourceFieldName = "Sources";
export const CategoryFieldName = "Categories";
export const CountryFieldName = "Countries";
